TestProject/TestProject/Models/SubjectGrade.cs
using System;
using System.Collections.Generic;

namespace TestProject.Models
{
    public partial class SubjectGrade
    {
        public string ClassName { get; set; }
        public int StudentId { get; set; }
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public int Grade { get; set; }
        public string SubjectName { get; set; }

        public Students Students { get; set; }
    }
}

TestProject/TestProject/ViewModels/StudentGradeOnSubject.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestProject.Models;

namespace TestProject.ViewModels
{
    public class StudentGradeOnSubject
    {
        public IEnumerable<Students> Students { get; set; }
        public IEnumerable<SubjectGradeModel> SubjectGrades { get; set; }
        public IEnumerable<Subjects> Subjects { get; set; }
    }
}

TestProject/TestProject/ViewModels/StudentGradeOnSubjectViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestProject.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TestProject.ViewModels
{
    public class StudentGradeOnSubjectViewModel
    {
        public IEnumerable<SubjectGrade> SubjectGrades { get; set; }
        public SelectList Subjects { get; set; }
        public SelectList Classes { get; set; }
    }
}

TestProject/TestProject/Controllers/SubjectGradeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using TestProject.Models;
using TestProject.Services;
using Microsoft.AspNetCore.Mvc.Rendering;
using NLog;
using TestProject.Descriptor;
using TestProject.ViewModels;

namespace TestProject.Controllers
{
    public class SubjectGradeController : Controller
    {
        DiaryDBContext db;
        private static Logger logger = LogManager.GetCurrentClassLogger();
        StudentService studentService;

        public SubjectGradeController(DiaryDBContext context, StudentService service)
        {
            db = context;
            studentService = service;
        }

        // вывод списка предметов с оценками выбранного ученика
        [HttpGet]
        public async Task<IActionResult> Grade(int id)
        {
            Students student = await studentService.GetStudent(id);
            var studentGrade = db.SubjectGrade.FromSqlInterpolated($"Select * From SubjectGrade Where StudentId={student.Id}").ToList();
            if (studentGrade != null)
                return View(studentGrade);
            return NotFound();
        }

        [Authorize(Roles = "admin, teacher")]
        // вызов формы для добавления новой оценки
        public IActionResult Add()
        {
            SelectList classes = new SelectList(db.Classes, "Name", "Name");
            ViewBag.Classes = classes;
            SelectList students = new SelectList(db.Students, "Id", "FullName");
            ViewBag.Students = students;
            SelectList subjects = new SelectList(db.Subjects, "Name", "Name");
            ViewBag.Subjects = subjects;
            return View();
        }

        [Authorize(Roles = "admin, teacher")]
        // добавление новой оценки в бд
        [HttpPost]
        public async Task<IActionResult> Add(SubjectGrade subjectGrade)
        {
            switch (subjectGrade.Date.DayOfWeek)
            {
                case DayOfWeek.Saturday:
                case DayOfWeek.Sunday:
                    return new ContentResult()
                    {
                        Content = Messages.CantAssessOnWeekends
                    };
            }
            switch (subjectGrade.Date.DayOfWeek)
            {
                case DayOfWeek.Monday:
                case DayOfWeek.Tuesday:
                case DayOfWeek.Wednesday:
                case DayOfWeek.Thursday:
                case DayOfWeek.Friday:
                    db.SubjectGrade.Add(subjectGrade);
                    await db.SaveChangesAsync();
                    break;
            }
            logger.Info($"Add grade (StudentID = {subjectGrade.StudentId}, Subject = {subjectGrade.SubjectName}) to the DiaryDB");
            return RedirectToAction("Grade", new { id = subjectGrade.StudentId });
        }

        [Authorize(Roles = "admin, teacher")]
        // вызов формы для ввода оценки
        [HttpGet]
        public async Task<IActionResult> Edit(int? id, string className, int? studentId, string subjectName)
        {
            if (id != null && className!=null && studentId != null && subjectName != null)
            {
                SubjectGrade subjectGrade =
                    await db.SubjectGrade
                    .FirstOrDefaultAsync(sb => sb.Id == id && sb.ClassName==className && sb.StudentId == studentId && sb.SubjectName == subjectName);
                if (subjectGrade != null)
                    return View(subjectGrade);
            }
            return NotFound();
        }

        [Authorize(Roles = "admin, teacher")]
        // сохранение оценки в бд
        [HttpPost]
        public async Task<IActionResult> Edit(SubjectGrade subjectGrade)
        {
            switch (subjectGrade.Date.DayOfWeek)
            {
                case DayOfWeek.Saturday:
                case DayOfWeek.Sunday:
                    return new ContentResult()
                    {
                        Content = Messages.CantAssessOnWeekends
                    };
            }
            switch (subjectGrade.Date.DayOfWeek)
            {
                case DayOfWeek.Monday:
                case DayOfWeek.Tuesday:
                case DayOfWeek.Wednesday:
                case DayOfWeek.Thursday:
                case DayOfWeek.Friday:
                    db.SubjectGrade.Update(subjectGrade);
                    await db.SaveChangesAsync();
                    break;
            }
            logger.Info($"Edit grade (ID = {subjectGrade.Id}, StudentID = {subjectGrade.StudentId}, Subject = {subjectGrade.SubjectName}) in the DiaryDB");
            return RedirectToAction("Grade", new { id = subjectGrade.StudentId });
        }

        [Authorize(Roles = "admin, teacher")]
        // показ удаляемой оценки ученика 
        [HttpGet]
        public async Task<IActionResult> Delete(int? studentId, string className, int? id, string subjectName)
        {
            if (studentId != null && className != null && id != null && subjectName != null)
            {
                SubjectGrade subjectGrade =
                    await db.SubjectGrade
                    .FirstOrDefaultAsync(s => s.StudentId == studentId && s.ClassName==className && s.Id == id && s.SubjectName == subjectName);
                if (subjectGrade != null)
                    return View(subjectGrade);
            }
            return NotFound();
        }

        [Authorize(Roles = "admin, teacher")]
        // удаление оценки ученика из бд
        [HttpPost]
        public async Task<IActionResult> Delete(SubjectGrade subjectGrade)
        {
            if (subjectGrade != null)
            {
                logger.Trace($"Grade (ID = {subjectGrade.Id}, StudentID = {subjectGrade.StudentId}, Subject = {subjectGrade.SubjectName}) was defined for remove from DiaryDB");
                db.SubjectGrade.Remove(subjectGrade);
                await db.SaveChangesAsync();
                logger.Info($"Grade (ID = {subjectGrade.Id}, StudentID = {subjectGrade.StudentId}, Subject = {subjectGrade.SubjectName}) was deleted from DiaryDB");
                return RedirectToAction("Grade", new { id = subjectGrade.StudentId });
            }
            logger.Error("Object SubjectGrade subjectGrade wasn't defined for remove from DiaryDB");
            return NotFound();
        }

        // вывод оценок студентов определенного класса с фильтрацией по предметам
        public IActionResult StudentGradeOnSubject(string className, int? studentId, string subjectName)
        {
            IQueryable<SubjectGrade> subjectGrades = db.SubjectGrade.Include(s => s.Students);
            if (className != null)
            {
                List<Subjects> subjects = db.Subjects.ToList();
                List<Classes> classes = db.Classes.ToList();
                subjectGrades = subjectGrades.Where(s => s.ClassName == className);

                StudentGradeOnSubjectViewModel studentGradeOnSubject =
                    new StudentGradeOnSubjectViewModel
                    {
                        Subjects = new SelectList(subjects, "Name", "Name"),
                        Classes = new SelectList(classes, "Name", "Name"),
                        SubjectGrades = subjectGrades.ToList()
                    };
                if (subjectName != null)
                    studentGradeOnSubject.SubjectGrades = subjectGrades.Where(s => s.ClassName == className && s.SubjectName == subjectName);
                return View(studentGradeOnSubject);
            }
            return NotFound();
        }
    }
}

TestProject/TestProject/Views/SubjectGrade/Add.cshtml
@model TestProject.Models.SubjectGrade
@{
    ViewBag.Title = "Добавление новой оценки";
}

<form asp-action="Add" asp-controller="SubjectGrade">
    <div class="form-group">
        <label asp-for="ClassName">Класс:</label>
        <select asp-for="ClassName" asp-items="ViewBag.Classes"></select>
    </div>
    <div class="form-group">
        <label asp-for="StudentId">Ученик:</label>
        <select asp-for="StudentId" asp-items="ViewBag.Students"></select>
    </div>
    <div class="form-group">
        <label asp-for="SubjectName">Предмет:</label>
        <select asp-for="SubjectName" asp-items="ViewBag.Subjects"></select>
    </div>
    <div class="form-group">
        <label asp-for="Date">Укажите дату:</label>
        <input type="date" asp-for="Date" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Grade">Укажите оценку:</label>
        <input type="number" min="1" max="12" value="1" asp-for="Grade" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Добавить" />
    </div>
</form>

TestProject/TestProject/Views/SubjectGrade/Delete.cshtml
@model TestProject.Models.SubjectGrade
@{
    ViewBag.Title = "Удаление оценки ученика";
}

<div>
    <dl>
        <dt>ID ученика:</dt>
        <dd>
            @Html.DisplayFor(model => model.StudentId)
        </dd>
        <dt>Название предмета:</dt>
        <dd>
            @Html.DisplayFor(model => model.SubjectName)
        </dd>
        <dt>Дата оценки:</dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>Оценка:</dt>
        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>
    </dl>
    <div>
        <form asp-controller="SubjectGrade" asp-action="Delete" asp-route-studentId="@Model.StudentId" asp-route-id="@Model.Id" asp-route-subjectName="@Model.SubjectName">
            <div class="form-group">
                <input type="submit" value="Удалить" />
            </div>
        </form>
    </div>
</div>

TestProject/TestProject/Views/SubjectGrade/Edit.cshtml
@model TestProject.Models.SubjectGrade
@{
    ViewBag.Title = "Внесение оценки по предмету";
}

<form asp-action="Edit" asp-controller="SubjectGrade" asp-route-id="@Model.Id" asp-route-className="@Model.ClassName" asp-route-studentId="@Model.StudentId" asp-route-subjectName="@Model.SubjectName">
    <div class="form-group">
        <label asp-for="Date">Укажите дату:</label>
        <input type="date" asp-for="Date" class="form-control" />
        <label asp-for="Grade">Укажите оценку:</label>
        <input type="number" min="1" max="12" value="1" asp-for="Grade" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Сохранить" />
    </div>
</form>

TestProject/TestProject/Views/SubjectGrade/Grade.cshtml
@model IEnumerable<TestProject.Models.SubjectGrade>
@{
    ViewBag.Title = "Оценки ученика";
}
<style>
    #right{text-align:right;}
</style>
    <h3>Оценки ученика</h3>
<table class="table">
    <tr>
        <td>Номер</td>
        <td>Дата</td>
        <td>Название предмета</td>
        <td id="right">Оценка</td>
    </tr>
    @foreach (var subjectGrade in Model)
    {
        <tr>
            <td>@subjectGrade.Id</td>
            <td>@subjectGrade.Date</td>
            <td>@subjectGrade.SubjectName</td>
            <td id="right"><a asp-action="Edit" asp-controller="SubjectGrade" asp-route-id="@subjectGrade.Id" asp-route-classname="@subjectGrade.ClassName" asp-route-studentId="@subjectGrade.StudentId" asp-route-subjectName="@subjectGrade.SubjectName">@subjectGrade.Grade</a></td>
            <td><a asp-action="Delete" asp-controller="SubjectGrade" asp-route-studentId="@subjectGrade.StudentId" asp-route-classname="@subjectGrade.ClassName" asp-route-id="@subjectGrade.Id" asp-route-subjectName="@subjectGrade.SubjectName">Удалить</a></td>
            <td><a asp-action="StudentGradeOnSubject" asp-controller="SubjectGrade" asp-route-className="@subjectGrade.ClassName" asp-route-studentId="@subjectGrade.StudentId" asp-route-subjectName="@subjectGrade.SubjectName">Перейти в журнал классов</a></td>
        </tr>
    }
    <tr>
        <td colspan="3"><b>Итоги</b></td>
        @if (Model.Any())
        {
            <td id="right"><b>Средняя оценка:  @Model.Average(g => g.Grade)</b></td>
        }
        else
        {
            <td id="right"><b>Средняя оценка:  0</b></td>
        }
    </tr>
</table>
<a asp-action="Add">Добавить</a>

TestProject/TestProject/Views/SubjectGrade/StudentGradeOnSubject.cshtml
@model TestProject.ViewModels.StudentGradeOnSubjectViewModel
@{
    ViewBag.Title = "Оценки учеников класса";
}
<style>
    #right {text-align: right;}
</style>

<h3>Журнал класса</h3>
<form method="get">
    <div class="form-inline form-group">
        <label>Выберите класс: </label>
        <select name="className" asp-items="Model.Classes" class="form-control"></select>
    </div>
    <div class="form-inline form-group">
        <label>Выберите предмет: </label>
        <select name="subjectName" asp-items="Model.Subjects" class="form-control"></select>
        <input type="submit" value="Фильтр" />
    </div>
</form>
<br />
<table class="table">
    <tr>
        <td>Номер ученика</td>
        <td>ФИО</td>
        <td>Предмет</td>
        <td>Дата</td>
        <td id="right">Оценка</td>
    </tr>
    @foreach (var students in Model.SubjectGrades)
    {
        <tr>
            <td>@students.StudentId</td>
            <td>@students.Students.FullName</td>
            <td>@students.SubjectName</td>
            <td>@students.Date.ToShortDateString()</td>
            <td id="right">@students.Grade</td>
        </tr>
    }
    <tr>
        <td colspan="4"><b>Итоги</b></td>
        @if (Model.SubjectGrades.Any())
        {
            <td id="right"><b>Средняя оценка:  @Model.SubjectGrades.Average(g => g.Grade)</b></td>
        }
        else
        {
            <td id="right"><b>Средняя оценка:  0</b></td>
        }
    </tr>
</table>