TestProject/TestProject/Models/ClassSubject.cs
using System;
using System.Collections.Generic;

namespace TestProject.Models
{
    public partial class ClassSubject
    {
        public string SubjectName { get; set; }
        public string ClassName { get; set; }
    }
}

TestProject/TestProject/ViewModels/StudentGradeOnSubject.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestProject.Models;

namespace TestProject.ViewModels
{
    public class StudentGradeOnSubject
    {
        public IEnumerable<Students> Students { get; set; }
        public IEnumerable<SubjectGradeModel> SubjectGrades { get; set; }
        public IEnumerable<Subjects> Subjects { get; set; }
    }
}

TestProject/TestProject/ViewModels/StudentGradeOnSubjectViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestProject.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TestProject.ViewModels
{
    public class StudentGradeOnSubjectViewModel
    {
        public IEnumerable<SubjectGrade> SubjectGrades { get; set; }
        public SelectList Subjects { get; set; }
        public SelectList Classes { get; set; }
    }
}

TestProject/TestProject/Controllers/ClassSubjectController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TestProject.Models;
using TestProject.Services;
using Microsoft.AspNetCore.Authorization;

namespace TestProject.Controllers
{
    public class ClassSubjectController : Controller
    {
        DiaryDBContext db;
        SubjectService subjectService;

        public ClassSubjectController(DiaryDBContext context, SubjectService service)
        {
            db = context;
            subjectService = service;
        }

        // вывод списка классов, у которых ведётся выбранный предмет
        [HttpGet]
        public async Task<IActionResult> Index(string name)
        {
            Subjects subject = await subjectService.GetSubject(name);
            if (subject.Name != null)
            {
                var classes =
                    db.ClassSubject.FromSqlInterpolated($"Select * From ClassSubject Where SubjectName={subject.Name}").ToList();
                if (classes != null)
                    return View(classes);
            }
            return NotFound();
        }

        [Authorize(Roles = "admin, director")]
        // вызов формы для добавления класса, изучающего предмет
        public IActionResult Add()
        {
            SelectList subjects = new SelectList(db.Subjects, "Name", "Name");
            ViewBag.Subjects = subjects;
            SelectList classes = new SelectList(db.Classes, "Name", "Name");
            ViewBag.Classes = classes;
            return View();
        }

        [Authorize(Roles = "admin, director")]
        // добавление нового класса, изучающего предмет в бд
        [HttpPost]
        public async Task<IActionResult> Add(ClassSubject classSubject)
        {
            db.ClassSubject.Add(classSubject);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", new { name = classSubject.SubjectName });
        }

        [Authorize(Roles = "admin, director")]
        // показ удаляемого класса, изучающего предмет
        [HttpGet]
        public async Task<IActionResult> Delete(string subjectName, string className)
        {
            if (subjectName != null && className != null)
            {
                ClassSubject classSubject =
                    await db.ClassSubject.FirstOrDefaultAsync(c => c.SubjectName == subjectName && c.ClassName == className);
                if (classSubject != null)
                    return View(classSubject);
            }
            return NotFound();
        }

        [Authorize(Roles = "admin, director")]
        // удаление класса, изучающего предмет из бд
        [HttpPost]
        public async Task<IActionResult> Delete(ClassSubject classSubject)
        {
            if (classSubject != null)
            {
                db.ClassSubject.Remove(classSubject);
                await db.SaveChangesAsync();
                return RedirectToAction("Index", new { name = classSubject.SubjectName });
            }
            return NotFound();
        }
    }
}

TestProject/TestProject/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using TestProject.Models;
using TestProject.Services;
using Microsoft.AspNetCore.Mvc.Rendering;
using NLog;
using Microsoft.AspNetCore.Authorization;

namespace TestProject.Controllers
{
    public class StudentsController : Controller
    {
        DiaryDBContext db;
        private static Logger logger = LogManager.GetCurrentClassLogger();
        ClassService classService;

        public StudentsController(DiaryDBContext context, ClassService service)
        {
            db = context;
            classService = service;
        }

        // вывод списка учеников выбранного класса
        [HttpGet]
        public async Task<IActionResult> Index(string name)
        {
            Classes stclass = await classService.GetClass(name);
            if (stclass.Name != null)
            {
                var students = 
                    db.Students.FromSqlInterpolated($"Select * From Students Where ClassName={stclass.Name}").ToList();
                if (students != null)
                    return View(students);
            }
            return NotFound();
        }

        [Authorize(Roles = "admin, director")]
        // вызов формы для добавления ученика класса
        public IActionResult Add()
        {
            SelectList classes = new SelectList(db.Classes, "Name", "Name");
            ViewBag.Classes = classes;
            return View();
        }

        [Authorize(Roles = "admin, director")]
        // добавление нового ученика класса в бд
        [HttpPost]
        public async Task<IActionResult> Add(Students student)
        {
            db.Students.Add(student);
            await db.SaveChangesAsync();
            logger.Info($"Add student (ID = {student.Id}) to the DiaryDB");
            return RedirectToAction("Index", new { name = student.ClassName });
        }

        [Authorize(Roles = "admin, director")]
        // показ удаляемого ученика класса
        [HttpGet]
        public async Task<IActionResult> Delete(string classname, int? id)
        {
            if (classname != null && id != null)
            {
                Students student =
                    await db.Students.FirstOrDefaultAsync(s => s.ClassName == classname && s.Id == id);
                if (student != null)
                    return View(student);
            }
            return NotFound();
        }

        [Authorize(Roles = "admin, director")]
        // удаление ученика класса из бд
        [HttpPost]
        public async Task<IActionResult> Delete(Students student)
        {
            if (student != null)
            {
                logger.Trace($"Student (ID = {student.Id}) was defined for remove from DiaryDB");
                db.Students.Remove(student);
                await db.SaveChangesAsync();
                logger.Info($"Student (ID = {student.Id}) was deleted from DiaryDB");
                return RedirectToAction("Index", new { name = student.ClassName });
            }
            logger.Error("Object Students student wasn't defined for remove from DiaryDB");
            return NotFound();
        }
    }
}

TestProject/TestProject/Views/ClassSubject/Add.cshtml
@model TestProject.Models.ClassSubject
@{
    ViewBag.Title = "Добавление нового класса, изучающего предмет";
}

<form asp-action="Add" asp-controller="ClassSubject">
    <div class="form-group">
        <label asp-for="SubjectName">Предмет:</label>
        <select asp-for="SubjectName" asp-items="ViewBag.Subjects"></select>
    </div>
    <div class="form-group">
        <label asp-for="ClassName">Класс:</label>
        <select asp-for="ClassName" asp-items="ViewBag.Classes"></select>
    </div>
    <div class="form-group">
        <input type="submit" value="Добавить" />
    </div>
</form>

TestProject/TestProject/Views/ClassSubject/Delete.cshtml
@model TestProject.Models.ClassSubject
@{
    ViewBag.Title = "Удаление класса, изучающего предмет";
}

<div>
    <dl>
        <dt>Предмет:</dt>
        <dd>
            @Html.DisplayFor(model => model.SubjectName)
        </dd>
        <dt>Класс:</dt>
        <dd>
            @Html.DisplayFor(model => model.ClassName)
        </dd>
    </dl>
    <div>
        <form asp-controller="ClassSubject" asp-action="Delete" asp-route-classname="@Model.ClassName" asp-route-subjectName="@Model.SubjectName">
            <div class="form-group">
                <input type="submit" value="Удалить" />
            </div>
        </form>
    </div>
</div>

TestProject/TestProject/Views/ClassSubject/Index.cshtml
@model IEnumerable<TestProject.Models.ClassSubject>
@{
    ViewBag.Title = "Классы, изучающие предмет";
}
<h3>Список классов, у которых ведётся предмет</h3>
<table class="table">
    <tr>
        <td>Название класса</td>
    </tr>
    @foreach (var studentClass in Model)
    {
        <tr>
            <td><a asp-action="Index" asp-controller="Students" asp-route-name="@studentClass.ClassName">@studentClass.ClassName</a></td>
            <td><a asp-action="Delete" asp-controller="ClassSubject" asp-route-className="@studentClass.ClassName" asp-route-subjectName="@studentClass.SubjectName">Удалить</a></td>
        </tr>
    }
</table>
<a asp-action="Add">Добавить</a>

TestProject/TestProject/Views/ClassSubject/StudentGradeOnSubject.cshtml
@model TestProject.ViewModels.StudentGradeOnSubjectViewModel
@{
    ViewBag.Title = "Оценки учеников класса";
}

<form method="get">
    <div class="form-inline form-group">
        <label class="custom-control-label">Выберите класс: </label>
        <select name="className" asp-items="Model.Classes" class="form-control"></select>
    </div>
    <div class="form-inline form-group">
        <label class="custom-control-label">Выберите предмет: </label>
        <select name="subjectName" asp-items="Model.Subjects" class="form-control"></select>
        <input type="submit" value="Фильтр" />
    </div>
</form>
<br />
<table class="table">
    <tr>
        <td>Номер ученика</td>
        <td>ФИО</td>
        <td>Предмет</td>
        @foreach (var date in Model.Students)
        {
            <td>@date.Date.ToShortDateString()</td>
        }
    </tr>
    @foreach (TestProject.ViewModels.StudentGradeModel students in Model.Students)
    {
        <tr>
            <td>@students.StudentID</td>
            <td>@students.FullName</td>
            <td>@students.SubjectName</td>
            <td>@students.Grade</td>
        </tr>
    }
</table>