TestProject/TestProject/Models/Subjects.cs
using System;
using System.Collections.Generic;
using TestProject.ViewModels;

namespace TestProject.Models
{
    public partial class Subjects
    {
        public string Name { get; set; }
    }
}

TestProject/TestProject/Controllers/ClassSubjectController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TestProject.Models;
using TestProject.Services;
using Microsoft.AspNetCore.Authorization;

namespace TestProject.Controllers
{
    public class ClassSubjectController : Controller
    {
        DiaryDBContext db;
        SubjectService subjectService;

        public ClassSubjectController(DiaryDBContext context, SubjectService service)
        {
            db = context;
            subjectService = service;
        }

        // вывод списка классов, у которых ведётся выбранный предмет
        [HttpGet]
        public async Task<IActionResult> Index(string name)
        {
            Subjects subject = await subjectService.GetSubject(name);
            if (subject.Name != null)
            {
                var classes =
                    db.ClassSubject.FromSqlInterpolated($"Select * From ClassSubject Where SubjectName={subject.Name}").ToList();
                if (classes != null)
                    return View(classes);
            }
            return NotFound();
        }

        [Authorize(Roles = "admin, director")]
        // вызов формы для добавления класса, изучающего предмет
        public IActionResult Add()
        {
            SelectList subjects = new SelectList(db.Subjects, "Name", "Name");
            ViewBag.Subjects = subjects;
            SelectList classes = new SelectList(db.Classes, "Name", "Name");
            ViewBag.Classes = classes;
            return View();
        }

        [Authorize(Roles = "admin, director")]
        // добавление нового класса, изучающего предмет в бд
        [HttpPost]
        public async Task<IActionResult> Add(ClassSubject classSubject)
        {
            db.ClassSubject.Add(classSubject);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", new { name = classSubject.SubjectName });
        }

        [Authorize(Roles = "admin, director")]
        // показ удаляемого класса, изучающего предмет
        [HttpGet]
        public async Task<IActionResult> Delete(string subjectName, string className)
        {
            if (subjectName != null && className != null)
            {
                ClassSubject classSubject =
                    await db.ClassSubject.FirstOrDefaultAsync(c => c.SubjectName == subjectName && c.ClassName == className);
                if (classSubject != null)
                    return View(classSubject);
            }
            return NotFound();
        }

        [Authorize(Roles = "admin, director")]
        // удаление класса, изучающего предмет из бд
        [HttpPost]
        public async Task<IActionResult> Delete(ClassSubject classSubject)
        {
            if (classSubject != null)
            {
                db.ClassSubject.Remove(classSubject);
                await db.SaveChangesAsync();
                return RedirectToAction("Index", new { name = classSubject.SubjectName });
            }
            return NotFound();
        }
    }
}

TestProject/TestProject/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using TestProject.Models;
using NLog;
using Microsoft.AspNetCore.Authorization;

namespace TestProject.Controllers
{
    public class SubjectsController : Controller
    {
        DiaryDBContext db;
        private static Logger logger = LogManager.GetCurrentClassLogger();

        public SubjectsController(DiaryDBContext context)
        {
            db = context;
        }

        //вывод списка предметов
        public IActionResult Index()
        {
            return View(db.Subjects.ToList());
        }

        [Authorize(Roles = "admin, director")]
        // вызов формы для добавления предмета
        public IActionResult Add()
        {
            return View();
        }

        [Authorize(Roles = "admin, director")]
        // добавление нового предмета в бд
        [HttpPost]
        public async Task<IActionResult> Add(Subjects subjects)
        {
            db.Subjects.Add(subjects);
            await db.SaveChangesAsync();
            logger.Info($"Add subject {subjects.Name} to the DiaryDB");
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "admin, director")]
        // показ удаляемого предмета
        [HttpGet]
        public async Task<IActionResult> Delete(string name)
        {
            if (name != null)
            {
                Subjects subjects =
                    await db.Subjects.FirstOrDefaultAsync(s => s.Name == name);
                if (subjects != null)
                    return View(subjects);
            }
            return NotFound();
        }

        [Authorize(Roles = "admin, director")]
        // удаление предмета из бд
        [HttpPost]
        public async Task<IActionResult> Delete(Subjects subjects)
        {
            if (subjects != null)
            {
                logger.Trace($"Subject {subjects.Name} was defined for remove from DiaryDB");
                db.Subjects.Remove(subjects);
                await db.SaveChangesAsync();
                logger.Info($"Subject {subjects.Name} was deleted from DiaryDB");
                return RedirectToAction("Index");
            }
            logger.Error("Object Subjects subjects wasn't defined for remove from DiaryDB");
            return NotFound();
        }
    }
}

TestProject/TestProject/Views/Subjects/Add.cshtml
@model TestProject.Models.Subjects
@{
    ViewBag.Title = "Добавление нового предмета";
}

<form asp-action="Add" asp-controller="Subjects">
    <div class="form-group">
        <label asp-for="Name">Название предмета</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Добавить" />
    </div>
</form>

TestProject/TestProject/Views/Subjects/Delete.cshtml
@model TestProject.Models.Subjects
@{
    ViewBag.Title = "Удаление предмета";
}

<div>
    <dl>
        <dt>Название</dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    <div>
        <form asp-controller="Subjects" asp-action="Delete" asp-route-name="@Model.Name">
            <div class="form-group">
                <input type="submit" value="Удалить" />
            </div>
        </form>
    </div>
</div>

TestProject/TestProject/Views/Subjects/Index.cshtml
@model IEnumerable<TestProject.Models.Subjects>
@{
    ViewBag.Title = "Предметы";
}
<h3>Предметы</h3>
<table class="table">
    <tr>
        <td>Название предмета</td>
    </tr>
    @foreach (var sub in Model)
    {
        <tr>
            <td><a asp-action="Index" asp-controller="ClassSubject" asp-route-name="@sub.Name">@sub.Name</a></td>
            <td>
                <a asp-action="Delete" asp-controller="Subjects" asp-route-name="@sub.Name">Удалить</a>
            </td>
        </tr>
    }
</table>
<a asp-action="Add">Добавить</a>